FROM node:14 AS builder

# Setting Home Directory for containers
WORKDIR /usr/src/app

COPY package*.json ./

## Installing dependencies
RUN npm ci

# Copying source code to the container
COPY . .
RUN npm run build


FROM nginx
COPY --from=builder /usr/src/app/build /usr/share/nginx/html
COPY  nginx.conf /etc/nginx/conf.d/default.conf
WORKDIR /usr/share/nginx/html
EXPOSE 80
