apiVersion: v1
kind: PersistentVolume
metadata:
  name: flytics-qa-volume
spec:
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4.2
  nfs:
    path: /home/tech/DevOps/kubernetes-volume/flytics/qa/mongodb
    server: 192.168.18.241
