apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flytics-mongodb-qa
  namespace: flytics
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 80Mi
  storageClassName: nfs
  # selector:
  #   matchLabels:
  #     name: "flytics-qa-volume"